<?php


/**
 * This class defines the structure of the 'cre8_content_type' table.
 *
 *
 * This class was autogenerated by Propel 1.5.0-dev on:
 *
 * śro, 27 sty 2010, 13:26:48
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.plugins.cre8CmsMenuPlugin.lib.model.map
 */
class cre8ContentTypeTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.cre8CmsMenuPlugin.lib.model.map.cre8ContentTypeTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('cre8_content_type');
		$this->setPhpName('cre8ContentType');
		$this->setClassname('cre8ContentType');
		$this->setPackage('plugins.cre8CmsMenuPlugin.lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('NAME', 'Name', 'VARCHAR', true, 128, null);
		$this->addColumn('DESCRIPTION', 'Description', 'LONGVARCHAR', false, null, null);
		$this->addColumn('LABEL', 'Label', 'VARCHAR', true, 128, null);
		$this->addColumn('PLUGIN_NAME', 'PluginName', 'VARCHAR', true, 128, null);
		$this->addColumn('DEFAULT_PATH', 'DefaultPath', 'VARCHAR', true, 255, null);
		$this->addColumn('THEME', 'Theme', 'VARCHAR', false, 128, null);
		$this->addColumn('TEMPLATE', 'Template', 'VARCHAR', false, 128, null);
		$this->addColumn('MODULE', 'Module', 'VARCHAR', false, 128, null);
		$this->addColumn('ACTION', 'Action', 'VARCHAR', false, 128, null);
		$this->addColumn('SLUG', 'Slug', 'VARCHAR', true, 128, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('cre8Content', 'cre8Content', RelationMap::ONE_TO_MANY, array('id' => 'content_type_id', ), 'CASCADE', null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // cre8ContentTypeTableMap
