<?php

/**
 * Base static class for performing query and update operations on the 'cre8_menu_item' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.0-dev on:
 *
 * śro, 27 sty 2010, 13:26:48
 *
 * @package    propel.generator.plugins.cre8CmsMenuPlugin.lib.model.om
 */
abstract class Basecre8MenuItemPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'cre8_menu_item';

	/** the related Propel class for this table */
	const OM_CLASS = 'cre8MenuItem';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'plugins.cre8CmsMenuPlugin.lib.model.cre8MenuItem';

	/** the related TableMap class for this table */
	const TM_CLASS = 'cre8MenuItemTableMap';
	
	/** The total number of columns. */
	const NUM_COLUMNS = 11;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the ID field */
	const ID = 'cre8_menu_item.ID';

	/** the column name for the LEFT field */
	const LEFT = 'cre8_menu_item.LEFT';

	/** the column name for the RIGHT field */
	const RIGHT = 'cre8_menu_item.RIGHT';

	/** the column name for the TREE_LEVEL field */
	const TREE_LEVEL = 'cre8_menu_item.TREE_LEVEL';

	/** the column name for the LABEL field */
	const LABEL = 'cre8_menu_item.LABEL';

	/** the column name for the CUSTOM_PATH field */
	const CUSTOM_PATH = 'cre8_menu_item.CUSTOM_PATH';

	/** the column name for the CONTENT_ID field */
	const CONTENT_ID = 'cre8_menu_item.CONTENT_ID';

	/** the column name for the IS_PRIMARY field */
	const IS_PRIMARY = 'cre8_menu_item.IS_PRIMARY';

	/** the column name for the DATE_PUBLISHED field */
	const DATE_PUBLISHED = 'cre8_menu_item.DATE_PUBLISHED';

	/** the column name for the DELETED_AT field */
	const DELETED_AT = 'cre8_menu_item.DELETED_AT';

	/** the column name for the SLUG field */
	const SLUG = 'cre8_menu_item.SLUG';

	/**
	 * An identiy map to hold any loaded instances of cre8MenuItem objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array cre8MenuItem[]
	 */
	public static $instances = array();


	// nested_set behavior
	
	/**
	 * Left column for the set
	 */
	const LEFT_COL = 'cre8_menu_item.LEFT';
	
	/**
	 * Right column for the set
	 */
	const RIGHT_COL = 'cre8_menu_item.RIGHT';
	
	/**
	 * Level column for the set
	 */
	const LEVEL_COL = 'cre8_menu_item.TREE_LEVEL';

	// symfony behavior
	
	/**
	 * Indicates whether the current model includes I18N.
	 */
	const IS_I18N = false;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Id', 'Left', 'Right', 'TreeLevel', 'Label', 'CustomPath', 'ContentId', 'IsPrimary', 'DatePublished', 'DeletedAt', 'Slug', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'left', 'right', 'treeLevel', 'label', 'customPath', 'contentId', 'isPrimary', 'datePublished', 'deletedAt', 'slug', ),
		BasePeer::TYPE_COLNAME => array (self::ID, self::LEFT, self::RIGHT, self::TREE_LEVEL, self::LABEL, self::CUSTOM_PATH, self::CONTENT_ID, self::IS_PRIMARY, self::DATE_PUBLISHED, self::DELETED_AT, self::SLUG, ),
		BasePeer::TYPE_RAW_COLNAME => array ('ID', 'LEFT', 'RIGHT', 'TREE_LEVEL', 'LABEL', 'CUSTOM_PATH', 'CONTENT_ID', 'IS_PRIMARY', 'DATE_PUBLISHED', 'DELETED_AT', 'SLUG', ),
		BasePeer::TYPE_FIELDNAME => array ('id', 'left', 'right', 'tree_level', 'label', 'custom_path', 'content_id', 'is_primary', 'date_published', 'deleted_at', 'slug', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'Left' => 1, 'Right' => 2, 'TreeLevel' => 3, 'Label' => 4, 'CustomPath' => 5, 'ContentId' => 6, 'IsPrimary' => 7, 'DatePublished' => 8, 'DeletedAt' => 9, 'Slug' => 10, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'left' => 1, 'right' => 2, 'treeLevel' => 3, 'label' => 4, 'customPath' => 5, 'contentId' => 6, 'isPrimary' => 7, 'datePublished' => 8, 'deletedAt' => 9, 'slug' => 10, ),
		BasePeer::TYPE_COLNAME => array (self::ID => 0, self::LEFT => 1, self::RIGHT => 2, self::TREE_LEVEL => 3, self::LABEL => 4, self::CUSTOM_PATH => 5, self::CONTENT_ID => 6, self::IS_PRIMARY => 7, self::DATE_PUBLISHED => 8, self::DELETED_AT => 9, self::SLUG => 10, ),
		BasePeer::TYPE_RAW_COLNAME => array ('ID' => 0, 'LEFT' => 1, 'RIGHT' => 2, 'TREE_LEVEL' => 3, 'LABEL' => 4, 'CUSTOM_PATH' => 5, 'CONTENT_ID' => 6, 'IS_PRIMARY' => 7, 'DATE_PUBLISHED' => 8, 'DELETED_AT' => 9, 'SLUG' => 10, ),
		BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'left' => 1, 'right' => 2, 'tree_level' => 3, 'label' => 4, 'custom_path' => 5, 'content_id' => 6, 'is_primary' => 7, 'date_published' => 8, 'deleted_at' => 9, 'slug' => 10, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, )
	);

	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. cre8MenuItemPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(cre8MenuItemPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      Criteria $criteria object containing the columns to add.
	 * @param      string   $alias    optional table alias
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria, $alias = null)
	{
		if (null === $alias) {
			$criteria->addSelectColumn(cre8MenuItemPeer::ID);
			$criteria->addSelectColumn(cre8MenuItemPeer::LEFT);
			$criteria->addSelectColumn(cre8MenuItemPeer::RIGHT);
			$criteria->addSelectColumn(cre8MenuItemPeer::TREE_LEVEL);
			$criteria->addSelectColumn(cre8MenuItemPeer::LABEL);
			$criteria->addSelectColumn(cre8MenuItemPeer::CUSTOM_PATH);
			$criteria->addSelectColumn(cre8MenuItemPeer::CONTENT_ID);
			$criteria->addSelectColumn(cre8MenuItemPeer::IS_PRIMARY);
			$criteria->addSelectColumn(cre8MenuItemPeer::DATE_PUBLISHED);
			$criteria->addSelectColumn(cre8MenuItemPeer::DELETED_AT);
			$criteria->addSelectColumn(cre8MenuItemPeer::SLUG);
		} else {
			$criteria->addSelectColumn($alias . '.ID');
			$criteria->addSelectColumn($alias . '.LEFT');
			$criteria->addSelectColumn($alias . '.RIGHT');
			$criteria->addSelectColumn($alias . '.TREE_LEVEL');
			$criteria->addSelectColumn($alias . '.LABEL');
			$criteria->addSelectColumn($alias . '.CUSTOM_PATH');
			$criteria->addSelectColumn($alias . '.CONTENT_ID');
			$criteria->addSelectColumn($alias . '.IS_PRIMARY');
			$criteria->addSelectColumn($alias . '.DATE_PUBLISHED');
			$criteria->addSelectColumn($alias . '.DELETED_AT');
			$criteria->addSelectColumn($alias . '.SLUG');
		}
	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(cre8MenuItemPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			cre8MenuItemPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(cre8MenuItemPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		// soft_delete behavior
		if (cre8MenuItemQuery::isSoftDeleteEnabled()) {
			$criteria->add(cre8MenuItemPeer::DELETED_AT, null, Criteria::ISNULL);
		} else {
			cre8MenuItemPeer::enableSoftDelete();
		}
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'Basecre8MenuItemPeer', $criteria, $con);
		}

		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     cre8MenuItem
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = cre8MenuItemPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return cre8MenuItemPeer::populateObjects(cre8MenuItemPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(cre8MenuItemPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			cre8MenuItemPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      cre8MenuItem $value A cre8MenuItem object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(cre8MenuItem $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A cre8MenuItem object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof cre8MenuItem) {
				$key = (string) $value->getId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or cre8MenuItem object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     cre8MenuItem Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Method to invalidate the instance pool of all tables related to cre8_menu_item
	 * by a foreign key with ON DELETE CASCADE
	 */
	public static function clearRelatedInstancePool()
	{
	}

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol] === null) {
			return null;
		}
		return (string) $row[$startcol];
	}

	/**
	 * Retrieves the primary key from the DB resultset row 
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, an array of the primary key columns will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     mixed The primary key of the row
	 */
	public static function getPrimaryKeyFromRow($row, $startcol = 0)
	{
		return (int) $row[$startcol];
	}
	
	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = cre8MenuItemPeer::getOMClass(false);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = cre8MenuItemPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = cre8MenuItemPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				cre8MenuItemPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}
	/**
	 * Populates an object of the default type or an object that inherit from the default.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     array (cre8MenuItem object, last column rank)
	 */
	public static function populateObject($row, $startcol = 0)
	{
		$key = cre8MenuItemPeer::getPrimaryKeyHashFromRow($row, $startcol);
		if (null !== ($obj = cre8MenuItemPeer::getInstanceFromPool($key))) {
			// We no longer rehydrate the object, since this can cause data loss.
			// See http://propel.phpdb.org/trac/ticket/509
			// $obj->hydrate($row, $startcol, true); // rehydrate
			$col = $startcol + cre8MenuItemPeer::NUM_COLUMNS;
		} else {
			$cls = cre8MenuItemPeer::OM_CLASS;
			$obj = new $cls();
			$col = $obj->hydrate($row, $startcol);
			cre8MenuItemPeer::addInstanceToPool($obj, $key);
		}
		return array($obj, $col);
	}

	/**
	 * Returns the number of rows matching criteria, joining the related cre8Content table
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoincre8Content(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(cre8MenuItemPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			cre8MenuItemPeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(cre8MenuItemPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(cre8MenuItemPeer::CONTENT_ID, cre8ContentPeer::ID, $join_behavior);

		// soft_delete behavior
		if (cre8MenuItemQuery::isSoftDeleteEnabled()) {
			$criteria->add(cre8MenuItemPeer::DELETED_AT, null, Criteria::ISNULL);
		} else {
			cre8MenuItemPeer::enableSoftDelete();
		}
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'Basecre8MenuItemPeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of cre8MenuItem objects pre-filled with their cre8Content objects.
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of cre8MenuItem objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoincre8Content(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		cre8MenuItemPeer::addSelectColumns($criteria);
		$startcol = (cre8MenuItemPeer::NUM_COLUMNS - cre8MenuItemPeer::NUM_LAZY_LOAD_COLUMNS);
		cre8ContentPeer::addSelectColumns($criteria);

		$criteria->addJoin(cre8MenuItemPeer::CONTENT_ID, cre8ContentPeer::ID, $join_behavior);

		// soft_delete behavior
		if (cre8MenuItemQuery::isSoftDeleteEnabled()) {
			$criteria->add(cre8MenuItemPeer::DELETED_AT, null, Criteria::ISNULL);
		} else {
			cre8MenuItemPeer::enableSoftDelete();
		}
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'Basecre8MenuItemPeer', $criteria, $con);
		}

		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = cre8MenuItemPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = cre8MenuItemPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$cls = cre8MenuItemPeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				cre8MenuItemPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = cre8ContentPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = cre8ContentPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$cls = cre8ContentPeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					cre8ContentPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (cre8MenuItem) to $obj2 (cre8Content)
				$obj2->addcre8MenuItem($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining all related tables
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAll(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(cre8MenuItemPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			cre8MenuItemPeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(cre8MenuItemPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(cre8MenuItemPeer::CONTENT_ID, cre8ContentPeer::ID, $join_behavior);

		// soft_delete behavior
		if (cre8MenuItemQuery::isSoftDeleteEnabled()) {
			$criteria->add(cre8MenuItemPeer::DELETED_AT, null, Criteria::ISNULL);
		} else {
			cre8MenuItemPeer::enableSoftDelete();
		}
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'Basecre8MenuItemPeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}

	/**
	 * Selects a collection of cre8MenuItem objects pre-filled with all related objects.
	 *
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of cre8MenuItem objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAll(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		cre8MenuItemPeer::addSelectColumns($criteria);
		$startcol2 = (cre8MenuItemPeer::NUM_COLUMNS - cre8MenuItemPeer::NUM_LAZY_LOAD_COLUMNS);

		cre8ContentPeer::addSelectColumns($criteria);
		$startcol3 = $startcol2 + (cre8ContentPeer::NUM_COLUMNS - cre8ContentPeer::NUM_LAZY_LOAD_COLUMNS);

		$criteria->addJoin(cre8MenuItemPeer::CONTENT_ID, cre8ContentPeer::ID, $join_behavior);

		// soft_delete behavior
		if (cre8MenuItemQuery::isSoftDeleteEnabled()) {
			$criteria->add(cre8MenuItemPeer::DELETED_AT, null, Criteria::ISNULL);
		} else {
			cre8MenuItemPeer::enableSoftDelete();
		}
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'Basecre8MenuItemPeer', $criteria, $con);
		}

		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = cre8MenuItemPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = cre8MenuItemPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$cls = cre8MenuItemPeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				cre8MenuItemPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

			// Add objects for joined cre8Content rows

			$key2 = cre8ContentPeer::getPrimaryKeyHashFromRow($row, $startcol2);
			if ($key2 !== null) {
				$obj2 = cre8ContentPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$cls = cre8ContentPeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					cre8ContentPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 loaded

				// Add the $obj1 (cre8MenuItem) to the collection in $obj2 (cre8Content)
				$obj2->addcre8MenuItem($obj1);
			} // if joined row not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}

	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * Add a TableMap instance to the database for this peer class.
	 */
	public static function buildTableMap()
	{
	  $dbMap = Propel::getDatabaseMap(Basecre8MenuItemPeer::DATABASE_NAME);
	  if (!$dbMap->hasTable(Basecre8MenuItemPeer::TABLE_NAME))
	  {
	    $dbMap->addTableObject(new cre8MenuItemTableMap());
	  }
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * If $withPrefix is true, the returned path
	 * uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @param      boolean $withPrefix Whether or not to return the path with the class name
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass($withPrefix = true)
	{
		return $withPrefix ? cre8MenuItemPeer::CLASS_DEFAULT : cre8MenuItemPeer::OM_CLASS;
	}

	/**
	 * Method perform an INSERT on the database, given a cre8MenuItem or Criteria object.
	 *
	 * @param      mixed $values Criteria or cre8MenuItem object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{
    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('Basecre8MenuItemPeer:doInsert:pre') as $sf_hook)
    {
      if (false !== $sf_hook_retval = call_user_func($sf_hook, 'Basecre8MenuItemPeer', $values, $con))
      {
        return $sf_hook_retval;
      }
    }

		if ($con === null) {
			$con = Propel::getConnection(cre8MenuItemPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from cre8MenuItem object
		}

		if ($criteria->containsKey(cre8MenuItemPeer::ID) && $criteria->keyContainsValue(cre8MenuItemPeer::ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.cre8MenuItemPeer::ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('Basecre8MenuItemPeer:doInsert:post') as $sf_hook)
    {
      call_user_func($sf_hook, 'Basecre8MenuItemPeer', $values, $con, $pk);
    }

		return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a cre8MenuItem or Criteria object.
	 *
	 * @param      mixed $values Criteria or cre8MenuItem object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{
    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('Basecre8MenuItemPeer:doUpdate:pre') as $sf_hook)
    {
      if (false !== $sf_hook_retval = call_user_func($sf_hook, 'Basecre8MenuItemPeer', $values, $con))
      {
        return $sf_hook_retval;
      }
    }

		if ($con === null) {
			$con = Propel::getConnection(cre8MenuItemPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(cre8MenuItemPeer::ID);
			$value = $criteria->remove(cre8MenuItemPeer::ID);
			if ($value) {
				$selectCriteria->add(cre8MenuItemPeer::ID, $value, $comparison);
			} else {
				$selectCriteria->setPrimaryTableName(cre8MenuItemPeer::TABLE_NAME);
			}

		} else { // $values is cre8MenuItem object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);

    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('Basecre8MenuItemPeer:doUpdate:post') as $sf_hook)
    {
      call_user_func($sf_hook, 'Basecre8MenuItemPeer', $values, $con, $ret);
    }

    return $ret;
	}

	/**
	 * Method to DELETE all rows from the cre8_menu_item table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doForceDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(cre8MenuItemPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(cre8MenuItemPeer::TABLE_NAME, $con);
			// Because this db requires some delete cascade/set null emulation, we have to
			// clear the cached instance *after* the emulation has happened (since
			// instances get re-added by the select statement contained therein).
			cre8MenuItemPeer::clearInstancePool();
			cre8MenuItemPeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a cre8MenuItem or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or cre8MenuItem object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doForceDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(cre8MenuItemPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			cre8MenuItemPeer::clearInstancePool();
			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof cre8MenuItem) { // it's a model object
			// invalidate the cache for this single object
			cre8MenuItemPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else { // it's a primary key, or an array of pks
			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(cre8MenuItemPeer::ID, (array) $values, Criteria::IN);
			// invalidate the cache for this object(s)
			foreach ((array) $values as $singleval) {
				cre8MenuItemPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);
			cre8MenuItemPeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given cre8MenuItem object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      cre8MenuItem $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(cre8MenuItem $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(cre8MenuItemPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(cre8MenuItemPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		return BasePeer::doValidate(cre8MenuItemPeer::DATABASE_NAME, cre8MenuItemPeer::TABLE_NAME, $columns);
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     cre8MenuItem
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = cre8MenuItemPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(cre8MenuItemPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(cre8MenuItemPeer::DATABASE_NAME);
		$criteria->add(cre8MenuItemPeer::ID, $pk);

		$v = cre8MenuItemPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(cre8MenuItemPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(cre8MenuItemPeer::DATABASE_NAME);
			$criteria->add(cre8MenuItemPeer::ID, $pks, Criteria::IN);
			$objs = cre8MenuItemPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

	// nested_set behavior
	
	/**
	 * Returns the root node for a given scope
	 *
	 * @param      PropelPDO $con	Connection to use.
	 * @return     cre8MenuItem			Propel object for root node
	 */
	public static function retrieveRoot(PropelPDO $con = null)
	{
		$c = new Criteria(cre8MenuItemPeer::DATABASE_NAME);
		$c->add(cre8MenuItemPeer::LEFT_COL, 1, Criteria::EQUAL);
	
		return cre8MenuItemPeer::doSelectOne($c, $con);
	}
	
	/**
	 * Returns the whole tree node for a given scope
	 *
	 * @param      Criteria $criteria	Optional Criteria to filter the query
	 * @param      PropelPDO $con	Connection to use.
	 * @return     cre8MenuItem			Propel object for root node
	 */
	public static function retrieveTree(Criteria $criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(cre8MenuItemPeer::DATABASE_NAME);
		}
		$criteria->addAscendingOrderByColumn(cre8MenuItemPeer::LEFT_COL);
		
		return cre8MenuItemPeer::doSelect($criteria, $con);
	}
	
	/**
	 * Tests if node is valid
	 *
	 * @param      cre8MenuItem $node	Propel object for src node
	 * @return     bool
	 */
	public static function isValid(cre8MenuItem $node = null)
	{
		if (is_object($node) && $node->getRightValue() > $node->getLeftValue()) {
			return true;
		} else {
			return false;
		}
	}
	
	/**
	 * Delete an entire tree
	 * 
	 * @param      PropelPDO $con	Connection to use.
	 *
	 * @return     int  The number of deleted nodes
	 */
	public static function deleteTree(PropelPDO $con = null)
	{
		return cre8MenuItemPeer::doDeleteAll($con);
	}
	
	/**
	 * Adds $delta to all L and R values that are >= $first and <= $last.
	 * '$delta' can also be negative.
	 *
	 * @param      int $delta		Value to be shifted by, can be negative
	 * @param      int $first		First node to be shifted
	 * @param      int $last			Last node to be shifted (optional)
	 * @param      PropelPDO $con		Connection to use.
	 */
	public static function shiftRLValues($delta, $first, $last = null, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(cre8MenuItemPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
	
		// Shift left column values
		$whereCriteria = new Criteria(cre8MenuItemPeer::DATABASE_NAME);
		$criterion = $whereCriteria->getNewCriterion(cre8MenuItemPeer::LEFT_COL, $first, Criteria::GREATER_EQUAL);
		if (null !== $last) {
			$criterion->addAnd($whereCriteria->getNewCriterion(cre8MenuItemPeer::LEFT_COL, $last, Criteria::LESS_EQUAL));
		}
		$whereCriteria->add($criterion);
		
		$valuesCriteria = new Criteria(cre8MenuItemPeer::DATABASE_NAME);
		$valuesCriteria->add(cre8MenuItemPeer::LEFT_COL, array('raw' => cre8MenuItemPeer::LEFT_COL . ' + ?', 'value' => $delta), Criteria::CUSTOM_EQUAL);
	
		BasePeer::doUpdate($whereCriteria, $valuesCriteria, $con);
	
		// Shift right column values
		$whereCriteria = new Criteria(cre8MenuItemPeer::DATABASE_NAME);
		$criterion = $whereCriteria->getNewCriterion(cre8MenuItemPeer::RIGHT_COL, $first, Criteria::GREATER_EQUAL);
		if (null !== $last) {
			$criterion->addAnd($whereCriteria->getNewCriterion(cre8MenuItemPeer::RIGHT_COL, $last, Criteria::LESS_EQUAL));
		}
		$whereCriteria->add($criterion);
	
		$valuesCriteria = new Criteria(cre8MenuItemPeer::DATABASE_NAME);
		$valuesCriteria->add(cre8MenuItemPeer::RIGHT_COL, array('raw' => cre8MenuItemPeer::RIGHT_COL . ' + ?', 'value' => $delta), Criteria::CUSTOM_EQUAL);
	
		BasePeer::doUpdate($whereCriteria, $valuesCriteria, $con);
	}
	
	/**
	 * Adds $delta to level for nodes having left value >= $first and right value <= $last.
	 * '$delta' can also be negative.
	 *
	 * @param      int $delta		Value to be shifted by, can be negative
	 * @param      int $first		First node to be shifted
	 * @param      int $last			Last node to be shifted
	 * @param      PropelPDO $con		Connection to use.
	 */
	public static function shiftLevel($delta, $first, $last, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(cre8MenuItemPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
	
		$whereCriteria = new Criteria(cre8MenuItemPeer::DATABASE_NAME);
		$whereCriteria->add(cre8MenuItemPeer::LEFT_COL, $first, Criteria::GREATER_EQUAL);
		$whereCriteria->add(cre8MenuItemPeer::RIGHT_COL, $last, Criteria::LESS_EQUAL);
		
		$valuesCriteria = new Criteria(cre8MenuItemPeer::DATABASE_NAME);
		$valuesCriteria->add(cre8MenuItemPeer::LEVEL_COL, array('raw' => cre8MenuItemPeer::LEVEL_COL . ' + ?', 'value' => $delta), Criteria::CUSTOM_EQUAL);
	
		BasePeer::doUpdate($whereCriteria, $valuesCriteria, $con);
	}
	
	/**
	 * Reload all already loaded nodes to sync them with updated db
	 *
	 * @param      PropelPDO $con		Connection to use.
	 */
	public static function updateLoadedNodes(PropelPDO $con = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			$keys = array();
			foreach (cre8MenuItemPeer::$instances as $obj) {
				$keys[] = $obj->getPrimaryKey();
			}
	
			if (!empty($keys)) {
				// We don't need to alter the object instance pool; we're just modifying these ones
				// already in the pool.
				$criteria = new Criteria(cre8MenuItemPeer::DATABASE_NAME);
				$criteria->add(cre8MenuItemPeer::ID, $keys, Criteria::IN);
	
				$stmt = cre8MenuItemPeer::doSelectStmt($criteria, $con);
				while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
					$key = cre8MenuItemPeer::getPrimaryKeyHashFromRow($row, 0);
					if (null !== ($object = cre8MenuItemPeer::getInstanceFromPool($key))) {
						$object->setLeftValue($row[1]);
						$object->setRightValue($row[2]);
						$object->setLevel($row[3]);
					}
				}
				$stmt->closeCursor();
			}
		}
	}
	
	/**
	 * Update the tree to allow insertion of a leaf at the specified position
	 *
	 * @param      int $left	left column value
	 * @param      PropelPDO $con	Connection to use.
	 */
	public static function makeRoomForLeaf($left, PropelPDO $con = null)
	{	
		// Update database nodes
		cre8MenuItemPeer::shiftRLValues(2, $left, null, $con);
	
		// Update all loaded nodes
		cre8MenuItemPeer::updateLoadedNodes($con);
	}
	
	/**
	 * Update the tree to allow insertion of a leaf at the specified position
	 *
	 * @param      PropelPDO $con	Connection to use.
	 */
	public static function fixLevels(PropelPDO $con = null)
	{
		$c = new Criteria();
		$c->addAscendingOrderByColumn(cre8MenuItemPeer::LEFT_COL);
		$stmt = cre8MenuItemPeer::doSelectStmt($c, $con);
		
		// set the class once to avoid overhead in the loop
		$cls = cre8MenuItemPeer::getOMClass(false);
		$level = null;
		// iterate over the statement
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
	
			// hydrate object
			$key = cre8MenuItemPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null === ($obj = cre8MenuItemPeer::getInstanceFromPool($key))) {
				$obj = new $cls();
				$obj->hydrate($row);
				cre8MenuItemPeer::addInstanceToPool($obj, $key);
			}
			
			// compute level
			// Algorithm shamelessly stolen from sfPropelActAsNestedSetBehaviorPlugin
			// Probably authored by Tristan Rivoallan
			if ($level === null) {
				$level = 0;
				$i = 0;
				$prev = array($obj->getRightValue());
			} else {
				while ($obj->getRightValue() > $prev[$i]) {
					$i--;
				}
				$level = ++$i;
				$prev[$i] = $obj->getRightValue();
			}
			
			// update level in node if necessary
			if ($obj->getLevel() !== $level) {
				$obj->setLevel($level);
				$obj->save($con);
			}
		}
		$stmt->closeCursor();
	}

	// soft_delete behavior
	
	/**
	 * Enable the soft_delete behavior for this model
	 */
	public static function enableSoftDelete()
	{
		cre8MenuItemQuery::enableSoftDelete();
	}
	
	/**
	 * Disable the soft_delete behavior for this model
	 */
	public static function disableSoftDelete()
	{
		cre8MenuItemQuery::disableSoftDelete();
	}
	
	/**
	 * Check the soft_delete behavior for this model
	 * @return boolean true if the soft_delete behavior is enabled
	 */
	public static function isSoftDeleteEnabled()
	{
		return cre8MenuItemQuery::isSoftDeleteEnabled();
	}
	
	/**
	 * Soft delete records, given a cre8MenuItem or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or cre8MenuItem object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		          rethrown wrapped into a PropelException.
	 */
	public static function doSoftDelete($values, PropelPDO $con = null)
	{
		if ($values instanceof Criteria) {
			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof cre8MenuItem) {
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else {
			// it must be the primary key
			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(cre8MenuItemPeer::ID, (array) $values, Criteria::IN);
		}
		$criteria->add(cre8MenuItemPeer::DELETED_AT, time());
		return cre8MenuItemPeer::doUpdate($criteria, $con);
	}
	
	/**
	 * Delete or soft delete records, depending on cre8MenuItemPeer::$softDelete
	 *
	 * @param      mixed $values Criteria or cre8MenuItem object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		          rethrown wrapped into a PropelException.
	 */
	public static function doDelete($values, PropelPDO $con = null)
	{
		if (cre8MenuItemPeer::isSoftDeleteEnabled()) {
			return cre8MenuItemPeer::doSoftDelete($values, $con);
		} else {
			return cre8MenuItemPeer::doForceDelete($values, $con);
		}	
	}
	/**
	 * Method to soft delete all rows from the cre8_menu_item table.
	 *
	 * @param      PropelPDO $con the connection to use
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		          rethrown wrapped into a PropelException.
	 */
	public static function doSoftDeleteAll(PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(cre8MenuItemPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$selectCriteria = new Criteria();
		$selectCriteria->add(cre8MenuItemPeer::DELETED_AT, null, Criteria::ISNULL);
		$selectCriteria->setDbName(cre8MenuItemPeer::DATABASE_NAME);
		$modifyCriteria = new Criteria();
		$modifyCriteria->add(cre8MenuItemPeer::DELETED_AT, time());
		return BasePeer::doUpdate($selectCriteria, $modifyCriteria, $con);
	}
	
	/**
	 * Delete or soft delete all records, depending on cre8MenuItemPeer::$softDelete
	 *
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		          rethrown wrapped into a PropelException.
	 */
	public static function doDeleteAll(PropelPDO $con = null)
	{
		if (cre8MenuItemPeer::isSoftDeleteEnabled()) {
			return cre8MenuItemPeer::doSoftDeleteAll($con);
		} else {
			return cre8MenuItemPeer::doForceDeleteAll($con);
		}	
	}

	// symfony behavior
	
	/**
	 * Returns an array of arrays that contain columns in each unique index.
	 *
	 * @return array
	 */
	static public function getUniqueColumnNames()
	{
	  return array(array('slug'));
	}

	// symfony_behaviors behavior
	
	/**
	 * Returns the name of the hook to call from inside the supplied method.
	 *
	 * @param string $method The calling method
	 *
	 * @return string A hook name for {@link sfMixer}
	 *
	 * @throws LogicException If the method name is not recognized
	 */
	static private function getMixerPreSelectHook($method)
	{
	  if (preg_match('/^do(Select|Count)(Join(All(Except)?)?|Stmt)?/', $method, $match))
	  {
	    return sprintf('Basecre8MenuItemPeer:%s:%1$s', 'Count' == $match[1] ? 'doCount' : $match[0]);
	  }
	
	  throw new LogicException(sprintf('Unrecognized function "%s"', $method));
	}

} // Basecre8MenuItemPeer

// This is the static code needed to register the TableMap for this table with the main Propel class.
//
Basecre8MenuItemPeer::buildTableMap();

