<?php

/**
 * Base class that represents a row from the 'cre8_content' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.0-dev on:
 *
 * śro, 27 sty 2010, 13:26:48
 *
 * @package    propel.generator.plugins.cre8CmsMenuPlugin.lib.model.om
 */
abstract class Basecre8Content extends BaseObject  implements Persistent
{

	/**
	 * Peer class name
	 */
  const PEER = 'cre8ContentPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        cre8ContentPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the content_type_id field.
	 * @var        int
	 */
	protected $content_type_id;

	/**
	 * The value for the date_published field.
	 * @var        string
	 */
	protected $date_published;

	/**
	 * The value for the custom_path field.
	 * @var        string
	 */
	protected $custom_path;

	/**
	 * The value for the theme field.
	 * @var        string
	 */
	protected $theme;

	/**
	 * The value for the template field.
	 * @var        string
	 */
	protected $template;

	/**
	 * The value for the module field.
	 * @var        string
	 */
	protected $module;

	/**
	 * The value for the action field.
	 * @var        string
	 */
	protected $action;

	/**
	 * The value for the page_title field.
	 * @var        string
	 */
	protected $page_title;

	/**
	 * The value for the meta_keywords field.
	 * @var        string
	 */
	protected $meta_keywords;

	/**
	 * The value for the meta_description field.
	 * @var        string
	 */
	protected $meta_description;

	/**
	 * The value for the slug field.
	 * @var        string
	 */
	protected $slug;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * @var        cre8ContentType
	 */
	protected $acre8ContentType;

	/**
	 * @var        array cre8MenuItem[] Collection to store aggregation of cre8MenuItem objects.
	 */
	protected $collcre8MenuItems;

	/**
	 * @var        Criteria The criteria used to select the current contents of collcre8MenuItems.
	 */
	private $lastcre8MenuItemCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [content_type_id] column value.
	 * 
	 * @return     int
	 */
	public function getContentTypeId()
	{
		return $this->content_type_id;
	}

	/**
	 * Get the [optionally formatted] temporal [date_published] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getDatePublished($format = 'Y-m-d H:i:s')
	{
		if ($this->date_published === null) {
			return null;
		}


		if ($this->date_published === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->date_published);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->date_published, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [custom_path] column value.
	 * 
	 * @return     string
	 */
	public function getCustomPath()
	{
		return $this->custom_path;
	}

	/**
	 * Get the [theme] column value.
	 * 
	 * @return     string
	 */
	public function getTheme()
	{
		return $this->theme;
	}

	/**
	 * Get the [template] column value.
	 * 
	 * @return     string
	 */
	public function getTemplate()
	{
		return $this->template;
	}

	/**
	 * Get the [module] column value.
	 * 
	 * @return     string
	 */
	public function getModule()
	{
		return $this->module;
	}

	/**
	 * Get the [action] column value.
	 * 
	 * @return     string
	 */
	public function getAction()
	{
		return $this->action;
	}

	/**
	 * Get the [page_title] column value.
	 * 
	 * @return     string
	 */
	public function getPageTitle()
	{
		return $this->page_title;
	}

	/**
	 * Get the [meta_keywords] column value.
	 * 
	 * @return     string
	 */
	public function getMetaKeywords()
	{
		return $this->meta_keywords;
	}

	/**
	 * Get the [meta_description] column value.
	 * 
	 * @return     string
	 */
	public function getMetaDescription()
	{
		return $this->meta_description;
	}

	/**
	 * Get the [slug] column value.
	 * 
	 * @return     string
	 */
	public function getSlug()
	{
		return $this->slug;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     cre8Content The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = cre8ContentPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [content_type_id] column.
	 * 
	 * @param      int $v new value
	 * @return     cre8Content The current object (for fluent API support)
	 */
	public function setContentTypeId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->content_type_id !== $v) {
			$this->content_type_id = $v;
			$this->modifiedColumns[] = cre8ContentPeer::CONTENT_TYPE_ID;
		}

		if ($this->acre8ContentType !== null && $this->acre8ContentType->getId() !== $v) {
			$this->acre8ContentType = null;
		}

		return $this;
	} // setContentTypeId()

	/**
	 * Sets the value of [date_published] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     cre8Content The current object (for fluent API support)
	 */
	public function setDatePublished($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->date_published !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->date_published !== null && $tmpDt = new DateTime($this->date_published)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->date_published = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = cre8ContentPeer::DATE_PUBLISHED;
			}
		} // if either are not null

		return $this;
	} // setDatePublished()

	/**
	 * Set the value of [custom_path] column.
	 * 
	 * @param      string $v new value
	 * @return     cre8Content The current object (for fluent API support)
	 */
	public function setCustomPath($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->custom_path !== $v) {
			$this->custom_path = $v;
			$this->modifiedColumns[] = cre8ContentPeer::CUSTOM_PATH;
		}

		return $this;
	} // setCustomPath()

	/**
	 * Set the value of [theme] column.
	 * 
	 * @param      string $v new value
	 * @return     cre8Content The current object (for fluent API support)
	 */
	public function setTheme($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->theme !== $v) {
			$this->theme = $v;
			$this->modifiedColumns[] = cre8ContentPeer::THEME;
		}

		return $this;
	} // setTheme()

	/**
	 * Set the value of [template] column.
	 * 
	 * @param      string $v new value
	 * @return     cre8Content The current object (for fluent API support)
	 */
	public function setTemplate($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->template !== $v) {
			$this->template = $v;
			$this->modifiedColumns[] = cre8ContentPeer::TEMPLATE;
		}

		return $this;
	} // setTemplate()

	/**
	 * Set the value of [module] column.
	 * 
	 * @param      string $v new value
	 * @return     cre8Content The current object (for fluent API support)
	 */
	public function setModule($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->module !== $v) {
			$this->module = $v;
			$this->modifiedColumns[] = cre8ContentPeer::MODULE;
		}

		return $this;
	} // setModule()

	/**
	 * Set the value of [action] column.
	 * 
	 * @param      string $v new value
	 * @return     cre8Content The current object (for fluent API support)
	 */
	public function setAction($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->action !== $v) {
			$this->action = $v;
			$this->modifiedColumns[] = cre8ContentPeer::ACTION;
		}

		return $this;
	} // setAction()

	/**
	 * Set the value of [page_title] column.
	 * 
	 * @param      string $v new value
	 * @return     cre8Content The current object (for fluent API support)
	 */
	public function setPageTitle($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->page_title !== $v) {
			$this->page_title = $v;
			$this->modifiedColumns[] = cre8ContentPeer::PAGE_TITLE;
		}

		return $this;
	} // setPageTitle()

	/**
	 * Set the value of [meta_keywords] column.
	 * 
	 * @param      string $v new value
	 * @return     cre8Content The current object (for fluent API support)
	 */
	public function setMetaKeywords($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->meta_keywords !== $v) {
			$this->meta_keywords = $v;
			$this->modifiedColumns[] = cre8ContentPeer::META_KEYWORDS;
		}

		return $this;
	} // setMetaKeywords()

	/**
	 * Set the value of [meta_description] column.
	 * 
	 * @param      string $v new value
	 * @return     cre8Content The current object (for fluent API support)
	 */
	public function setMetaDescription($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->meta_description !== $v) {
			$this->meta_description = $v;
			$this->modifiedColumns[] = cre8ContentPeer::META_DESCRIPTION;
		}

		return $this;
	} // setMetaDescription()

	/**
	 * Set the value of [slug] column.
	 * 
	 * @param      string $v new value
	 * @return     cre8Content The current object (for fluent API support)
	 */
	public function setSlug($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->slug !== $v) {
			$this->slug = $v;
			$this->modifiedColumns[] = cre8ContentPeer::SLUG;
		}

		return $this;
	} // setSlug()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     cre8Content The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = cre8ContentPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     cre8Content The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = cre8ContentPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->content_type_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->date_published = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->custom_path = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->theme = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->template = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->module = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->action = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->page_title = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->meta_keywords = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->meta_description = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->slug = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->created_at = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->updated_at = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			return $startcol + 14; // 14 = cre8ContentPeer::NUM_COLUMNS - cre8ContentPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating cre8Content object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->acre8ContentType !== null && $this->content_type_id !== $this->acre8ContentType->getId()) {
			$this->acre8ContentType = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(cre8ContentPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = cre8ContentPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->acre8ContentType = null;
			$this->collcre8MenuItems = null;
			$this->lastcre8MenuItemCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(cre8ContentPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('Basecre8Content:delete:pre') as $callable)
			{
			  if ($ret = call_user_func($callable, $this, $con))
			  {
			    return;
			  }
			}

			if ($ret) {
				cre8ContentPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('Basecre8Content:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$con->commit();
				$this->setDeleted(true);
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(cre8ContentPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// timestampable behavior
			if (!$this->isColumnModified(cre8ContentPeer::UPDATED_AT)) {
				$this->setUpdatedAt(time());
			}
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('Basecre8Content:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// timestampable behavior
				if (!$this->isColumnModified(cre8ContentPeer::CREATED_AT)) {
					$this->setCreatedAt(time());
				}
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('Basecre8Content:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				cre8ContentPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->acre8ContentType !== null) {
				if ($this->acre8ContentType->isModified() || $this->acre8ContentType->isNew()) {
					$affectedRows += $this->acre8ContentType->save($con);
				}
				$this->setcre8ContentType($this->acre8ContentType);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = cre8ContentPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = cre8ContentPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += cre8ContentPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collcre8MenuItems !== null) {
				foreach ($this->collcre8MenuItems as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->acre8ContentType !== null) {
				if (!$this->acre8ContentType->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->acre8ContentType->getValidationFailures());
				}
			}


			if (($retval = cre8ContentPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collcre8MenuItems !== null) {
					foreach ($this->collcre8MenuItems as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = cre8ContentPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getContentTypeId();
				break;
			case 2:
				return $this->getDatePublished();
				break;
			case 3:
				return $this->getCustomPath();
				break;
			case 4:
				return $this->getTheme();
				break;
			case 5:
				return $this->getTemplate();
				break;
			case 6:
				return $this->getModule();
				break;
			case 7:
				return $this->getAction();
				break;
			case 8:
				return $this->getPageTitle();
				break;
			case 9:
				return $this->getMetaKeywords();
				break;
			case 10:
				return $this->getMetaDescription();
				break;
			case 11:
				return $this->getSlug();
				break;
			case 12:
				return $this->getCreatedAt();
				break;
			case 13:
				return $this->getUpdatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param     string  $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 *                    BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. 
	 *                    Defaults to BasePeer::TYPE_PHPNAME.
	 * @param     boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns. Defaults to TRUE.
	 * @param     boolean $includeForeignObjects (optional) Whether to include hydrated related objects. Default to FALSE.
	 *
	 * @return    array an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true, $includeForeignObjects = false)
	{
		$keys = cre8ContentPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getContentTypeId(),
			$keys[2] => $this->getDatePublished(),
			$keys[3] => $this->getCustomPath(),
			$keys[4] => $this->getTheme(),
			$keys[5] => $this->getTemplate(),
			$keys[6] => $this->getModule(),
			$keys[7] => $this->getAction(),
			$keys[8] => $this->getPageTitle(),
			$keys[9] => $this->getMetaKeywords(),
			$keys[10] => $this->getMetaDescription(),
			$keys[11] => $this->getSlug(),
			$keys[12] => $this->getCreatedAt(),
			$keys[13] => $this->getUpdatedAt(),
		);
		if ($includeForeignObjects) {
			if (null !== $this->acre8ContentType) {
				$result['cre8ContentType'] = $this->acre8ContentType->toArray($keyType, $includeLazyLoadColumns, true);
			}
		}
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = cre8ContentPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setContentTypeId($value);
				break;
			case 2:
				$this->setDatePublished($value);
				break;
			case 3:
				$this->setCustomPath($value);
				break;
			case 4:
				$this->setTheme($value);
				break;
			case 5:
				$this->setTemplate($value);
				break;
			case 6:
				$this->setModule($value);
				break;
			case 7:
				$this->setAction($value);
				break;
			case 8:
				$this->setPageTitle($value);
				break;
			case 9:
				$this->setMetaKeywords($value);
				break;
			case 10:
				$this->setMetaDescription($value);
				break;
			case 11:
				$this->setSlug($value);
				break;
			case 12:
				$this->setCreatedAt($value);
				break;
			case 13:
				$this->setUpdatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = cre8ContentPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setContentTypeId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setDatePublished($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setCustomPath($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setTheme($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setTemplate($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setModule($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setAction($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setPageTitle($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setMetaKeywords($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setMetaDescription($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setSlug($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setCreatedAt($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setUpdatedAt($arr[$keys[13]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(cre8ContentPeer::DATABASE_NAME);

		if ($this->isColumnModified(cre8ContentPeer::ID)) $criteria->add(cre8ContentPeer::ID, $this->id);
		if ($this->isColumnModified(cre8ContentPeer::CONTENT_TYPE_ID)) $criteria->add(cre8ContentPeer::CONTENT_TYPE_ID, $this->content_type_id);
		if ($this->isColumnModified(cre8ContentPeer::DATE_PUBLISHED)) $criteria->add(cre8ContentPeer::DATE_PUBLISHED, $this->date_published);
		if ($this->isColumnModified(cre8ContentPeer::CUSTOM_PATH)) $criteria->add(cre8ContentPeer::CUSTOM_PATH, $this->custom_path);
		if ($this->isColumnModified(cre8ContentPeer::THEME)) $criteria->add(cre8ContentPeer::THEME, $this->theme);
		if ($this->isColumnModified(cre8ContentPeer::TEMPLATE)) $criteria->add(cre8ContentPeer::TEMPLATE, $this->template);
		if ($this->isColumnModified(cre8ContentPeer::MODULE)) $criteria->add(cre8ContentPeer::MODULE, $this->module);
		if ($this->isColumnModified(cre8ContentPeer::ACTION)) $criteria->add(cre8ContentPeer::ACTION, $this->action);
		if ($this->isColumnModified(cre8ContentPeer::PAGE_TITLE)) $criteria->add(cre8ContentPeer::PAGE_TITLE, $this->page_title);
		if ($this->isColumnModified(cre8ContentPeer::META_KEYWORDS)) $criteria->add(cre8ContentPeer::META_KEYWORDS, $this->meta_keywords);
		if ($this->isColumnModified(cre8ContentPeer::META_DESCRIPTION)) $criteria->add(cre8ContentPeer::META_DESCRIPTION, $this->meta_description);
		if ($this->isColumnModified(cre8ContentPeer::SLUG)) $criteria->add(cre8ContentPeer::SLUG, $this->slug);
		if ($this->isColumnModified(cre8ContentPeer::CREATED_AT)) $criteria->add(cre8ContentPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(cre8ContentPeer::UPDATED_AT)) $criteria->add(cre8ContentPeer::UPDATED_AT, $this->updated_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(cre8ContentPeer::DATABASE_NAME);
		$criteria->add(cre8ContentPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Returns true if the primary key for this object is null.
	 * @return     boolean
	 */
	public function isPrimaryKeyNull()
	{
		return null === $this->getId();
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of cre8Content (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{
		$copyObj->setContentTypeId($this->content_type_id);
		$copyObj->setDatePublished($this->date_published);
		$copyObj->setCustomPath($this->custom_path);
		$copyObj->setTheme($this->theme);
		$copyObj->setTemplate($this->template);
		$copyObj->setModule($this->module);
		$copyObj->setAction($this->action);
		$copyObj->setPageTitle($this->page_title);
		$copyObj->setMetaKeywords($this->meta_keywords);
		$copyObj->setMetaDescription($this->meta_description);
		$copyObj->setSlug($this->slug);
		$copyObj->setCreatedAt($this->created_at);
		$copyObj->setUpdatedAt($this->updated_at);

		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getcre8MenuItems() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addcre8MenuItem($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);
		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value
	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     cre8Content Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     cre8ContentPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new cre8ContentPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a cre8ContentType object.
	 *
	 * @param      cre8ContentType $v
	 * @return     cre8Content The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setcre8ContentType(cre8ContentType $v = null)
	{
		if ($v === null) {
			$this->setContentTypeId(NULL);
		} else {
			$this->setContentTypeId($v->getId());
		}

		$this->acre8ContentType = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the cre8ContentType object, it will not be re-added.
		if ($v !== null) {
			$v->addcre8Content($this);
		}

		return $this;
	}


	/**
	 * Get the associated cre8ContentType object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     cre8ContentType The associated cre8ContentType object.
	 * @throws     PropelException
	 */
	public function getcre8ContentType(PropelPDO $con = null)
	{
		if ($this->acre8ContentType === null && ($this->content_type_id !== null)) {
			$this->acre8ContentType = cre8ContentTypePeer::retrieveByPk($this->content_type_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->acre8ContentType->addcre8Contents($this);
			 */
		}
		return $this->acre8ContentType;
	}

	/**
	 * Clears out the collcre8MenuItems collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addcre8MenuItems()
	 */
	public function clearcre8MenuItems()
	{
		$this->collcre8MenuItems = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collcre8MenuItems collection (array).
	 *
	 * By default this just sets the collcre8MenuItems collection to an empty array (like clearcollcre8MenuItems());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initcre8MenuItems()
	{
		$this->collcre8MenuItems = array();
	}

	/**
	 * Gets an array of cre8MenuItem objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this cre8Content has previously been saved, it will retrieve
	 * related cre8MenuItems from storage. If this cre8Content is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array cre8MenuItem[]
	 * @throws     PropelException
	 */
	public function getcre8MenuItems($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(cre8ContentPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collcre8MenuItems === null) {
			if ($this->isNew()) {
			   $this->collcre8MenuItems = array();
			} else {

				$criteria->add(cre8MenuItemPeer::CONTENT_ID, $this->id);

				cre8MenuItemPeer::addSelectColumns($criteria);
				$this->collcre8MenuItems = cre8MenuItemPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(cre8MenuItemPeer::CONTENT_ID, $this->id);

				cre8MenuItemPeer::addSelectColumns($criteria);
				if (!isset($this->lastcre8MenuItemCriteria) || !$this->lastcre8MenuItemCriteria->equals($criteria)) {
					$this->collcre8MenuItems = cre8MenuItemPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastcre8MenuItemCriteria = $criteria;
		return $this->collcre8MenuItems;
	}

	/**
	 * Returns the number of related cre8MenuItem objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related cre8MenuItem objects.
	 * @throws     PropelException
	 */
	public function countcre8MenuItems(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(cre8ContentPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collcre8MenuItems === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(cre8MenuItemPeer::CONTENT_ID, $this->id);

				$count = cre8MenuItemPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(cre8MenuItemPeer::CONTENT_ID, $this->id);

				if (!isset($this->lastcre8MenuItemCriteria) || !$this->lastcre8MenuItemCriteria->equals($criteria)) {
					$count = cre8MenuItemPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collcre8MenuItems);
				}
			} else {
				$count = count($this->collcre8MenuItems);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a cre8MenuItem object to this object
	 * through the cre8MenuItem foreign key attribute.
	 *
	 * @param      cre8MenuItem $l cre8MenuItem
	 * @return     void
	 * @throws     PropelException
	 */
	public function addcre8MenuItem(cre8MenuItem $l)
	{
		if ($this->collcre8MenuItems === null) {
			$this->initcre8MenuItems();
		}
		if (!in_array($l, $this->collcre8MenuItems, true)) { // only add it if the **same** object is not already associated
			array_push($this->collcre8MenuItems, $l);
			$l->setcre8Content($this);
		}
	}

	/**
	 * Clears the current object and sets all attributes to their default values
	 */
	public function clear()
	{
		$this->id = null;
		$this->content_type_id = null;
		$this->date_published = null;
		$this->custom_path = null;
		$this->theme = null;
		$this->template = null;
		$this->module = null;
		$this->action = null;
		$this->page_title = null;
		$this->meta_keywords = null;
		$this->meta_description = null;
		$this->slug = null;
		$this->created_at = null;
		$this->updated_at = null;
		$this->clearAllReferences();
		$this->setNew(true);
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collcre8MenuItems) {
				foreach ((array) $this->collcre8MenuItems as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collcre8MenuItems = null;
		$this->acre8ContentType = null;
	}

	// timestampable behavior
	
	/**
	 * Mark the current object so that the update date doesn't get updated during next save
	 *
	 * @return     cre8Content The current object (for fluent API support)
	 */
	public function keepUpdateDateUnchanged()
	{
		$this->modifiedColumns[] = cre8ContentPeer::UPDATED_AT;
		return $this;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('Basecre8Content:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method Basecre8Content::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // Basecre8Content
