<?php

/**
 * Base class that represents a row from the 'cre8_menu_item' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.0-dev on:
 *
 * śro, 27 sty 2010, 13:26:48
 *
 * @package    propel.generator.plugins.cre8CmsMenuPlugin.lib.model.om
 */
abstract class Basecre8MenuItem extends BaseObject  implements Persistent
{

	/**
	 * Peer class name
	 */
  const PEER = 'cre8MenuItemPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        cre8MenuItemPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the left field.
	 * @var        int
	 */
	protected $left;

	/**
	 * The value for the right field.
	 * @var        int
	 */
	protected $right;

	/**
	 * The value for the tree_level field.
	 * @var        int
	 */
	protected $tree_level;

	/**
	 * The value for the label field.
	 * @var        string
	 */
	protected $label;

	/**
	 * The value for the custom_path field.
	 * @var        string
	 */
	protected $custom_path;

	/**
	 * The value for the content_id field.
	 * @var        int
	 */
	protected $content_id;

	/**
	 * The value for the is_primary field.
	 * Note: this column has a database default value of: false
	 * @var        boolean
	 */
	protected $is_primary;

	/**
	 * The value for the date_published field.
	 * @var        string
	 */
	protected $date_published;

	/**
	 * The value for the deleted_at field.
	 * @var        string
	 */
	protected $deleted_at;

	/**
	 * The value for the slug field.
	 * @var        string
	 */
	protected $slug;

	/**
	 * @var        cre8Content
	 */
	protected $acre8Content;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// nested_set behavior
	
	/**
	 * Queries to be executed in the save transaction
	 * @var        array
	 */
	protected $nestedSetQueries = array();

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->is_primary = false;
	}

	/**
	 * Initializes internal state of Basecre8MenuItem object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [left] column value.
	 * 
	 * @return     int
	 */
	public function getLeft()
	{
		return $this->left;
	}

	/**
	 * Get the [right] column value.
	 * 
	 * @return     int
	 */
	public function getRight()
	{
		return $this->right;
	}

	/**
	 * Get the [tree_level] column value.
	 * 
	 * @return     int
	 */
	public function getTreeLevel()
	{
		return $this->tree_level;
	}

	/**
	 * Get the [label] column value.
	 * 
	 * @return     string
	 */
	public function getLabel()
	{
		return $this->label;
	}

	/**
	 * Get the [custom_path] column value.
	 * 
	 * @return     string
	 */
	public function getCustomPath()
	{
		return $this->custom_path;
	}

	/**
	 * Get the [content_id] column value.
	 * 
	 * @return     int
	 */
	public function getContentId()
	{
		return $this->content_id;
	}

	/**
	 * Get the [is_primary] column value.
	 * 
	 * @return     boolean
	 */
	public function getIsPrimary()
	{
		return $this->is_primary;
	}

	/**
	 * Get the [optionally formatted] temporal [date_published] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getDatePublished($format = 'Y-m-d H:i:s')
	{
		if ($this->date_published === null) {
			return null;
		}


		if ($this->date_published === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->date_published);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->date_published, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [deleted_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getDeletedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->deleted_at === null) {
			return null;
		}


		if ($this->deleted_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->deleted_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->deleted_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [slug] column value.
	 * 
	 * @return     string
	 */
	public function getSlug()
	{
		return $this->slug;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     cre8MenuItem The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = cre8MenuItemPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [left] column.
	 * 
	 * @param      int $v new value
	 * @return     cre8MenuItem The current object (for fluent API support)
	 */
	public function setLeft($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->left !== $v) {
			$this->left = $v;
			$this->modifiedColumns[] = cre8MenuItemPeer::LEFT;
		}

		return $this;
	} // setLeft()

	/**
	 * Set the value of [right] column.
	 * 
	 * @param      int $v new value
	 * @return     cre8MenuItem The current object (for fluent API support)
	 */
	public function setRight($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->right !== $v) {
			$this->right = $v;
			$this->modifiedColumns[] = cre8MenuItemPeer::RIGHT;
		}

		return $this;
	} // setRight()

	/**
	 * Set the value of [tree_level] column.
	 * 
	 * @param      int $v new value
	 * @return     cre8MenuItem The current object (for fluent API support)
	 */
	public function setTreeLevel($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->tree_level !== $v) {
			$this->tree_level = $v;
			$this->modifiedColumns[] = cre8MenuItemPeer::TREE_LEVEL;
		}

		return $this;
	} // setTreeLevel()

	/**
	 * Set the value of [label] column.
	 * 
	 * @param      string $v new value
	 * @return     cre8MenuItem The current object (for fluent API support)
	 */
	public function setLabel($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->label !== $v) {
			$this->label = $v;
			$this->modifiedColumns[] = cre8MenuItemPeer::LABEL;
		}

		return $this;
	} // setLabel()

	/**
	 * Set the value of [custom_path] column.
	 * 
	 * @param      string $v new value
	 * @return     cre8MenuItem The current object (for fluent API support)
	 */
	public function setCustomPath($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->custom_path !== $v) {
			$this->custom_path = $v;
			$this->modifiedColumns[] = cre8MenuItemPeer::CUSTOM_PATH;
		}

		return $this;
	} // setCustomPath()

	/**
	 * Set the value of [content_id] column.
	 * 
	 * @param      int $v new value
	 * @return     cre8MenuItem The current object (for fluent API support)
	 */
	public function setContentId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->content_id !== $v) {
			$this->content_id = $v;
			$this->modifiedColumns[] = cre8MenuItemPeer::CONTENT_ID;
		}

		if ($this->acre8Content !== null && $this->acre8Content->getId() !== $v) {
			$this->acre8Content = null;
		}

		return $this;
	} // setContentId()

	/**
	 * Set the value of [is_primary] column.
	 * 
	 * @param      boolean $v new value
	 * @return     cre8MenuItem The current object (for fluent API support)
	 */
	public function setIsPrimary($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->is_primary !== $v || $this->isNew()) {
			$this->is_primary = $v;
			$this->modifiedColumns[] = cre8MenuItemPeer::IS_PRIMARY;
		}

		return $this;
	} // setIsPrimary()

	/**
	 * Sets the value of [date_published] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     cre8MenuItem The current object (for fluent API support)
	 */
	public function setDatePublished($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->date_published !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->date_published !== null && $tmpDt = new DateTime($this->date_published)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->date_published = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = cre8MenuItemPeer::DATE_PUBLISHED;
			}
		} // if either are not null

		return $this;
	} // setDatePublished()

	/**
	 * Sets the value of [deleted_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     cre8MenuItem The current object (for fluent API support)
	 */
	public function setDeletedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->deleted_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->deleted_at !== null && $tmpDt = new DateTime($this->deleted_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->deleted_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = cre8MenuItemPeer::DELETED_AT;
			}
		} // if either are not null

		return $this;
	} // setDeletedAt()

	/**
	 * Set the value of [slug] column.
	 * 
	 * @param      string $v new value
	 * @return     cre8MenuItem The current object (for fluent API support)
	 */
	public function setSlug($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->slug !== $v) {
			$this->slug = $v;
			$this->modifiedColumns[] = cre8MenuItemPeer::SLUG;
		}

		return $this;
	} // setSlug()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->is_primary !== false) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->left = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->right = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->tree_level = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->label = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->custom_path = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->content_id = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->is_primary = ($row[$startcol + 7] !== null) ? (boolean) $row[$startcol + 7] : null;
			$this->date_published = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->deleted_at = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->slug = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			return $startcol + 11; // 11 = cre8MenuItemPeer::NUM_COLUMNS - cre8MenuItemPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating cre8MenuItem object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->acre8Content !== null && $this->content_id !== $this->acre8Content->getId()) {
			$this->acre8Content = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(cre8MenuItemPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = cre8MenuItemPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->acre8Content = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(cre8MenuItemPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// nested_set behavior
			if ($this->isRoot()) {
				throw new PropelException('Deletion of a root node is disabled for nested sets. Use cre8MenuItemPeer::deleteTree() instead to delete an entire tree');
			}
			$this->deleteDescendants($con);

			// soft_delete behavior
			if (!empty($ret) && cre8MenuItemQuery::isSoftDeleteEnabled()) {
				$this->setDeletedAt(time());
				$this->save();
				$con->commit();
				return;
			}
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('Basecre8MenuItem:delete:pre') as $callable)
			{
			  if ($ret = call_user_func($callable, $this, $con))
			  {
			    return;
			  }
			}

			if ($ret) {
				cre8MenuItemPeer::doDelete($this, $con);
				$this->postDelete($con);
				// nested_set behavior
				// fill up the room that was used by the node
				cre8MenuItemPeer::shiftRLValues(-2, $this->getRightValue() + 1, null, $con);

				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('Basecre8MenuItem:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$con->commit();
				$this->setDeleted(true);
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(cre8MenuItemPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// nested_set behavior
			$this->processNestedSetQueries($con);
			// sluggable behavior
			if (!$this->isColumnModified(cre8MenuItemPeer::SLUG)) {
				$this->setSlug($this->createSlug());
			} else {
				$this->setSlug($this->makeSlugUnique($this->getSlug()));
			}
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('Basecre8MenuItem:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('Basecre8MenuItem:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				cre8MenuItemPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->acre8Content !== null) {
				if ($this->acre8Content->isModified() || $this->acre8Content->isNew()) {
					$affectedRows += $this->acre8Content->save($con);
				}
				$this->setcre8Content($this->acre8Content);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = cre8MenuItemPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = cre8MenuItemPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += cre8MenuItemPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->acre8Content !== null) {
				if (!$this->acre8Content->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->acre8Content->getValidationFailures());
				}
			}


			if (($retval = cre8MenuItemPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = cre8MenuItemPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getLeft();
				break;
			case 2:
				return $this->getRight();
				break;
			case 3:
				return $this->getTreeLevel();
				break;
			case 4:
				return $this->getLabel();
				break;
			case 5:
				return $this->getCustomPath();
				break;
			case 6:
				return $this->getContentId();
				break;
			case 7:
				return $this->getIsPrimary();
				break;
			case 8:
				return $this->getDatePublished();
				break;
			case 9:
				return $this->getDeletedAt();
				break;
			case 10:
				return $this->getSlug();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param     string  $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 *                    BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. 
	 *                    Defaults to BasePeer::TYPE_PHPNAME.
	 * @param     boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns. Defaults to TRUE.
	 * @param     boolean $includeForeignObjects (optional) Whether to include hydrated related objects. Default to FALSE.
	 *
	 * @return    array an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true, $includeForeignObjects = false)
	{
		$keys = cre8MenuItemPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getLeft(),
			$keys[2] => $this->getRight(),
			$keys[3] => $this->getTreeLevel(),
			$keys[4] => $this->getLabel(),
			$keys[5] => $this->getCustomPath(),
			$keys[6] => $this->getContentId(),
			$keys[7] => $this->getIsPrimary(),
			$keys[8] => $this->getDatePublished(),
			$keys[9] => $this->getDeletedAt(),
			$keys[10] => $this->getSlug(),
		);
		if ($includeForeignObjects) {
			if (null !== $this->acre8Content) {
				$result['cre8Content'] = $this->acre8Content->toArray($keyType, $includeLazyLoadColumns, true);
			}
		}
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = cre8MenuItemPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setLeft($value);
				break;
			case 2:
				$this->setRight($value);
				break;
			case 3:
				$this->setTreeLevel($value);
				break;
			case 4:
				$this->setLabel($value);
				break;
			case 5:
				$this->setCustomPath($value);
				break;
			case 6:
				$this->setContentId($value);
				break;
			case 7:
				$this->setIsPrimary($value);
				break;
			case 8:
				$this->setDatePublished($value);
				break;
			case 9:
				$this->setDeletedAt($value);
				break;
			case 10:
				$this->setSlug($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = cre8MenuItemPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setLeft($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setRight($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setTreeLevel($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setLabel($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setCustomPath($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setContentId($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setIsPrimary($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setDatePublished($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setDeletedAt($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setSlug($arr[$keys[10]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(cre8MenuItemPeer::DATABASE_NAME);

		if ($this->isColumnModified(cre8MenuItemPeer::ID)) $criteria->add(cre8MenuItemPeer::ID, $this->id);
		if ($this->isColumnModified(cre8MenuItemPeer::LEFT)) $criteria->add(cre8MenuItemPeer::LEFT, $this->left);
		if ($this->isColumnModified(cre8MenuItemPeer::RIGHT)) $criteria->add(cre8MenuItemPeer::RIGHT, $this->right);
		if ($this->isColumnModified(cre8MenuItemPeer::TREE_LEVEL)) $criteria->add(cre8MenuItemPeer::TREE_LEVEL, $this->tree_level);
		if ($this->isColumnModified(cre8MenuItemPeer::LABEL)) $criteria->add(cre8MenuItemPeer::LABEL, $this->label);
		if ($this->isColumnModified(cre8MenuItemPeer::CUSTOM_PATH)) $criteria->add(cre8MenuItemPeer::CUSTOM_PATH, $this->custom_path);
		if ($this->isColumnModified(cre8MenuItemPeer::CONTENT_ID)) $criteria->add(cre8MenuItemPeer::CONTENT_ID, $this->content_id);
		if ($this->isColumnModified(cre8MenuItemPeer::IS_PRIMARY)) $criteria->add(cre8MenuItemPeer::IS_PRIMARY, $this->is_primary);
		if ($this->isColumnModified(cre8MenuItemPeer::DATE_PUBLISHED)) $criteria->add(cre8MenuItemPeer::DATE_PUBLISHED, $this->date_published);
		if ($this->isColumnModified(cre8MenuItemPeer::DELETED_AT)) $criteria->add(cre8MenuItemPeer::DELETED_AT, $this->deleted_at);
		if ($this->isColumnModified(cre8MenuItemPeer::SLUG)) $criteria->add(cre8MenuItemPeer::SLUG, $this->slug);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(cre8MenuItemPeer::DATABASE_NAME);
		$criteria->add(cre8MenuItemPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Returns true if the primary key for this object is null.
	 * @return     boolean
	 */
	public function isPrimaryKeyNull()
	{
		return null === $this->getId();
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of cre8MenuItem (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{
		$copyObj->setLeft($this->left);
		$copyObj->setRight($this->right);
		$copyObj->setTreeLevel($this->tree_level);
		$copyObj->setLabel($this->label);
		$copyObj->setCustomPath($this->custom_path);
		$copyObj->setContentId($this->content_id);
		$copyObj->setIsPrimary($this->is_primary);
		$copyObj->setDatePublished($this->date_published);
		$copyObj->setDeletedAt($this->deleted_at);
		$copyObj->setSlug($this->slug);

		$copyObj->setNew(true);
		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value
	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     cre8MenuItem Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     cre8MenuItemPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new cre8MenuItemPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a cre8Content object.
	 *
	 * @param      cre8Content $v
	 * @return     cre8MenuItem The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setcre8Content(cre8Content $v = null)
	{
		if ($v === null) {
			$this->setContentId(NULL);
		} else {
			$this->setContentId($v->getId());
		}

		$this->acre8Content = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the cre8Content object, it will not be re-added.
		if ($v !== null) {
			$v->addcre8MenuItem($this);
		}

		return $this;
	}


	/**
	 * Get the associated cre8Content object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     cre8Content The associated cre8Content object.
	 * @throws     PropelException
	 */
	public function getcre8Content(PropelPDO $con = null)
	{
		if ($this->acre8Content === null && ($this->content_id !== null)) {
			$this->acre8Content = cre8ContentPeer::retrieveByPk($this->content_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->acre8Content->addcre8MenuItems($this);
			 */
		}
		return $this->acre8Content;
	}

	/**
	 * Clears the current object and sets all attributes to their default values
	 */
	public function clear()
	{
		$this->id = null;
		$this->left = null;
		$this->right = null;
		$this->tree_level = null;
		$this->label = null;
		$this->custom_path = null;
		$this->content_id = null;
		$this->is_primary = null;
		$this->date_published = null;
		$this->deleted_at = null;
		$this->slug = null;
		$this->clearAllReferences();
		$this->applyDefaultValues();
		$this->setNew(true);
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

		$this->acre8Content = null;
	}

	// nested_set behavior
	
	/**
	 * Execute queries that were saved to be run inside the save transaction
	 */
	protected function processNestedSetQueries($con)
	{
		foreach ($this->nestedSetQueries as $query) {
			$query['arguments'][]= $con;
			call_user_func_array($query['callable'], $query['arguments']);
		}
		$this->nestedSetQueries = array();
	}
	
	/**
	 * Wraps the getter for the nested set left value
	 *
	 * @return     int
	 */
	public function getLeftValue()
	{
		return $this->left;
	}
	
	/**
	 * Wraps the getter for the nested set right value
	 *
	 * @return     int
	 */
	public function getRightValue()
	{
		return $this->right;
	}
	
	/**
	 * Wraps the getter for the nested set level
	 *
	 * @return     int
	 */
	public function getLevel()
	{
		return $this->tree_level;
	}
	
	/**
	 * Set the value left column
	 *
	 * @param      int $v new value
	 * @return     cre8MenuItem The current object (for fluent API support)
	 */
	public function setLeftValue($v)
	{
		return $this->setLeft($v);
	}
	
	/**
	 * Set the value of right column
	 *
	 * @param      int $v new value
	 * @return     cre8MenuItem The current object (for fluent API support)
	 */
	public function setRightValue($v)
	{
		return $this->setRight($v);
	}
	
	/**
	 * Set the value of level column
	 *
	 * @param      int $v new value
	 * @return     cre8MenuItem The current object (for fluent API support)
	 */
	public function setLevel($v)
	{
		return $this->setTreeLevel($v);
	}
	
	/**
	 * Creates the supplied node as the root node.
	 *
	 * @return     cre8MenuItem The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function makeRoot()
	{
		if ($this->getLeftValue() || $this->getRightValue()) {
			throw new PropelException('Cannot turn an existing node into a root node.');
		}
	
		$this->setLeftValue(1);
		$this->setRightValue(2);
		$this->setLevel(0);
		return $this;
	}
	
	/**
	 * Tests if onbject is a node, i.e. if it is inserted in the tree
	 *
	 * @return     bool
	 */
	public function isInTree()
	{
		return $this->getLeftValue() > 0 && $this->getRightValue() > $this->getLeftValue();
	}
	
	/**
	 * Tests if node is a root
	 *
	 * @return     bool
	 */
	public function isRoot()
	{
		return $this->isInTree() && $this->getLeftValue() == 1;
	}
	
	/**
	 * Tests if node is a leaf
	 *
	 * @return     bool
	 */
	public function isLeaf()
	{
		return $this->isInTree() &&  ($this->getRightValue() - $this->getLeftValue()) == 1;
	}
	
	/**
	 * Tests if node is a descendant of another node
	 *
	 * @param      cre8MenuItem $node Propel node object
	 * @return     bool
	 */
	public function isDescendantOf($parent)
	{
		return $this->isInTree() && $this->getLeftValue() > $parent->getLeftValue() && $this->getRightValue() < $parent->getRightValue();
	}
	
	/**
	 * Tests if node is a ancestor of another node
	 *
	 * @param      cre8MenuItem $node Propel node object
	 * @return     bool
	 */
	public function isAncestorOf($child)
	{
		return $child->isDescendantOf($this);
	}
	
	/**
	 * Tests if object has an ancestor
	 *
	 * @param      PropelPDO $con Connection to use.
	 * @return     bool
	 */
	public function hasParent(PropelPDO $con = null)
	{
		return $this->getLevel() > 0;
	}
	
	/**
	 * Gets ancestor for the given node if it exists
	 * The result is cached so further calls to the same method don't issue any queries
	 *
	 * @param      PropelPDO $con Connection to use.
	 * @return     mixed 		Propel object if exists else false
	 */
	public function getParent(PropelPDO $con = null)
	{
		if(!$this->hasParent()) {
			return null;
		} else {
			$c = new Criteria(cre8MenuItemPeer::DATABASE_NAME);
			$c->add(cre8MenuItemPeer::LEFT_COL, $this->getLeftValue(), Criteria::LESS_THAN);
			$c->add(cre8MenuItemPeer::RIGHT_COL, $this->getRightValue(), Criteria::GREATER_THAN);		
			$c->addAscendingOrderByColumn(cre8MenuItemPeer::RIGHT_COL);
			return cre8MenuItemPeer::doSelectOne($c, $con);
		}
	}
	
	/**
	 * Determines if the node has previous sibling
	 *
	 * @param      PropelPDO $con Connection to use.
	 * @return     bool
	 */
	public function hasPrevSibling(PropelPDO $con = null)
	{
		if (!cre8MenuItemPeer::isValid($this)) {
			return false;
		}
		$c = new Criteria(cre8MenuItemPeer::DATABASE_NAME);
		$c->add(cre8MenuItemPeer::RIGHT_COL, $this->getLeftValue() - 1, Criteria::EQUAL);
		return cre8MenuItemPeer::doCount($c, $con) > 0;
	}
	
	/**
	 * Gets previous sibling for the given node if it exists
	 *
	 * @param      PropelPDO $con Connection to use.
	 * @return     mixed 		Propel object if exists else false
	 */
	public function getPrevSibling(PropelPDO $con = null)
	{
		$c = new Criteria(cre8MenuItemPeer::DATABASE_NAME);
		$c->add(cre8MenuItemPeer::RIGHT_COL, $this->getLeftValue() - 1, Criteria::EQUAL);
		return cre8MenuItemPeer::doSelectOne($c, $con);
	}
	
	/**
	 * Determines if the node has next sibling
	 *
	 * @param      PropelPDO $con Connection to use.
	 * @return     bool
	 */
	public function hasNextSibling(PropelPDO $con = null)
	{
		if (!cre8MenuItemPeer::isValid($this)) {
			return false;
		}
		$c = new Criteria(cre8MenuItemPeer::DATABASE_NAME);
		$c->add(cre8MenuItemPeer::LEFT_COL, $this->getRightValue() + 1, Criteria::EQUAL);		
		return cre8MenuItemPeer::doCount($c, $con) > 0;
	}
	
	/**
	 * Gets next sibling for the given node if it exists
	 *
	 * @param      PropelPDO $con Connection to use.
	 * @return     mixed 		Propel object if exists else false
	 */
	public function getNextSibling(PropelPDO $con = null)
	{
		$c = new Criteria(cre8MenuItemPeer::DATABASE_NAME);
		$c->add(cre8MenuItemPeer::LEFT_COL, $this->getRightValue() + 1, Criteria::EQUAL);		
		return cre8MenuItemPeer::doSelectOne($c, $con);
	}
	
	/**
	 * Tests if node has children
	 *
	 * @return     bool
	 */
	public function hasChildren()
	{
		return ($this->getRightValue() - $this->getLeftValue()) > 1;
	}
	
	/**
	 * Gets the children of the given node
	 *
	 * @param      Criteria $criteria Criteria to filter results. 
	 * @param      PropelPDO $con Connection to use.
	 * @return     array 		List of cre8MenuItem objects
	 */
	public function getChildren(Criteria $criteria = null, PropelPDO $con = null)
	{
		if($this->isLeaf()) {
			// save one query
			return array();
		}
		$criteria = $this->getDescendantsCriteria($criteria);
		$criteria->add(cre8MenuItemPeer::LEVEL_COL, $this->getLevel() + 1, Criteria::EQUAL);
	
		return cre8MenuItemPeer::doSelect($criteria, $con);
	}
	
	/**
	 * Gets number of children for the given node
	 *
	 * @param      Criteria $criteria Criteria to filter results. 
	 * @param      PropelPDO $con Connection to use.
	 * @return     int 		Number of children
	 */
	public function getNumberOfChildren(Criteria $criteria = null, PropelPDO $con = null)
	{
		if($this->isLeaf()) {
			// save one query
			return 0;
		}
		$criteria = $this->getDescendantsCriteria($criteria);
		$criteria->add(cre8MenuItemPeer::LEVEL_COL, $this->getLevel() + 1, Criteria::EQUAL);
		
		return cre8MenuItemPeer::doCount($criteria, $con);
	}
	
	/**
	 * Gets the first child of the given node
	 *
	 * @param      Criteria $criteria Criteria to filter results. 
	 * @param      PropelPDO $con Connection to use.
	 * @return     array 		List of cre8MenuItem objects
	 */
	public function getFirstChild(Criteria $criteria = null, PropelPDO $con = null)
	{
		if($this->isLeaf()) {
			// save one query
			return array();
		}
		$criteria = $this->getDescendantsCriteria($criteria);
		$criteria->add(cre8MenuItemPeer::LEVEL_COL, $this->getLevel() + 1, Criteria::EQUAL);
	
		return cre8MenuItemPeer::doSelectOne($criteria, $con);
	}
	
	/**
	 * Gets the last child of the given node
	 *
	 * @param      Criteria $criteria Criteria to filter results. 
	 * @param      PropelPDO $con Connection to use.
	 * @return     array 		List of cre8MenuItem objects
	 */
	public function getLastChild(Criteria $criteria = null, PropelPDO $con = null)
	{
		if($this->isLeaf()) {
			// save one query
			return array();
		}
		if ($criteria === null) {
			$criteria = new Criteria(cre8MenuItemPeer::DATABASE_NAME);
		}
		$criteria->addDescendingOrderByColumn(cre8MenuItemPeer::RIGHT_COL);
	
		return $this->getFirstChild($criteria, $con);
	}
	
	/**
	 * Gets the siblings of the given node
	 *
	 * @param      bool			$includeNode Whether to include the current node or not
	 * @param      Criteria $criteria Criteria to filter results. 
	 * @param      PropelPDO $con Connection to use.
	 *
	 * @return     array 		List of cre8MenuItem objects
	 */
	public function getSiblings($includeNode = false, Criteria $criteria = null, PropelPDO $con = null)
	{
		if($this->isRoot()) {
			// save one query
			return array();
		}
		$parent = $this->getParent($con);
		$siblings = array();
		foreach ($parent->getChildren($criteria, $con) as $sibling) {
			if ($this->equals($sibling) && !$includeNode) {
				continue;
			}
			$siblings[] = $sibling;
		}
		return $siblings;
	}
	
	/**
	 * Gets descendants for the given node
	 *
	 * @param      Criteria $criteria Criteria to filter results. 
	 * @param      PropelPDO $con Connection to use.
	 * @return     array 		List of cre8MenuItem objects
	 */
	public function getDescendants(Criteria $criteria = null, PropelPDO $con = null)
	{
		if($this->isLeaf()) {
			// save one query
			return array();
		}
		$criteria = $this->getDescendantsCriteria($criteria);
		
		return cre8MenuItemPeer::doSelect($criteria, $con);
	}
	
	/**
	 * Gets number of descendants for the given node
	 *
	 * @param      Criteria $criteria Criteria to filter results. 
	 * @param      PropelPDO $con Connection to use.
	 * @return     int 		Number of descendants
	 */
	public function getNumberOfDescendants(Criteria $criteria = null, PropelPDO $con = null)
	{
		if($this->isLeaf()) {
			// save one query
			return 0;
		}
		$criteria = $this->getDescendantsCriteria($criteria);
		
		return cre8MenuItemPeer::doCount($criteria, $con);
	}
	
	/**
	 * Gets descendants for the given node, plus the current node
	 *
	 * @param      Criteria $criteria Criteria to filter results. 
	 * @param      PropelPDO $con Connection to use.
	 * @return     array 		List of cre8MenuItem objects
	 */
	public function getBranch(Criteria $criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(cre8MenuItemPeer::DATABASE_NAME);
		}
		$criteria->add(cre8MenuItemPeer::LEFT_COL, $this->getLeftValue(), Criteria::GREATER_EQUAL);
		$criteria->add(cre8MenuItemPeer::RIGHT_COL, $this->getRightValue(), Criteria::LESS_EQUAL);		
		$criteria->addAscendingOrderByColumn(cre8MenuItemPeer::LEFT_COL);
			
		return cre8MenuItemPeer::doSelect($criteria, $con);
	}
	
	/**
	 * Gets a Criteria for the descendants for the given node
	 *
	 * @param      Criteria $criteria Criteria to filter results
	 * 
	 * @return     Criteria Criteria to find the descendants
	 */
	protected function getDescendantsCriteria(Criteria $criteria = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(cre8MenuItemPeer::DATABASE_NAME);
		}
		$criteria->add(cre8MenuItemPeer::LEFT_COL, $this->getLeftValue(), Criteria::GREATER_THAN);
		$criteria->add(cre8MenuItemPeer::RIGHT_COL, $this->getRightValue(), Criteria::LESS_THAN);		
		$criteria->addAscendingOrderByColumn(cre8MenuItemPeer::LEFT_COL);
	
		return $criteria;
	}
	
	/**
	 * Gets ancestors for the given node, starting with the root node
	 * Use it for breadcrumb paths for instance
	 *
	 * @param      Criteria $criteria Criteria to filter results. 
	 * @param      PropelPDO $con Connection to use.
	 * @return     array 		List of cre8MenuItem objects
	 */
	public function getAncestors(Criteria $criteria = null, PropelPDO $con = null)
	{
		if($this->isRoot()) {
			// save one query
			return array();
		}
		if ($criteria === null) {
			$criteria = new Criteria(cre8MenuItemPeer::DATABASE_NAME);
		}
		if ($con === null) {
			$con = Propel::getConnection(cre8MenuItemPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		$criteria->add(cre8MenuItemPeer::LEFT_COL, $this->getLeftValue(), Criteria::LESS_THAN);
		$criteria->add(cre8MenuItemPeer::RIGHT_COL, $this->getRightValue(), Criteria::GREATER_THAN);		
		$criteria->addAscendingOrderByColumn(cre8MenuItemPeer::LEFT_COL);
	
		return cre8MenuItemPeer::doSelect($criteria, $con);
	}
	
	/**
	 * Inserts the given $child node as first child of current
	 * The modifications in the current object and the tree
	 * are not persisted until the child object is saved.
	 *
	 * @param      cre8MenuItem $child	Propel object for child node
	 *
	 * @return     cre8MenuItem The current Propel object
	 */
	public function addChild(cre8MenuItem $child)
	{
		if ($this->isNew()) {
			throw new PropelException('A cre8MenuItem object must not be new to accept children.');
		}
		$child->insertAsFirstChildOf($this);
		return $this;
	}
	
	/**
	 * Inserts the current node as first child of given $parent node
	 * The modifications in the current object and the tree
	 * are not persisted until the current object is saved.
	 *
	 * @param      cre8MenuItem $parent	Propel object for parent node
	 *
	 * @return     cre8MenuItem The current Propel object
	 */
	public function insertAsFirstChildOf($parent)
	{
		if ($this->isInTree()) {
			throw new PropelException('A cre8MenuItem object must not already be in the tree to be inserted. Use the moveToFirstChildOf() instead.');
		}
		$left = $parent->getLeftValue() + 1;
		// Update node properties
		$this->setLeftValue($left);
		$this->setRightValue($left + 1);
		$this->setLevel($parent->getLevel() + 1);
		// Keep the tree modification query for the save() transaction
		$this->nestedSetQueries []= array(
			'callable'  => array('cre8MenuItemPeer', 'makeRoomForLeaf'),
			'arguments' => array($left)
		);
		return $this;
	}
	
	/**
	 * Inserts the current node as last child of given $parent node
	 * The modifications in the current object and the tree
	 * are not persisted until the current object is saved.
	 *
	 * @param      cre8MenuItem $parent	Propel object for parent node
	 *
	 * @return     cre8MenuItem The current Propel object
	 */
	public function insertAsLastChildOf($parent)
	{
		if ($this->isInTree()) {
			throw new PropelException('A cre8MenuItem object must not already be in the tree to be inserted. Use the moveToLastChildOf() instead.');
		}
		$left = $parent->getRightValue();
		// Update node properties
		$this->setLeftValue($left);
		$this->setRightValue($left + 1);
		$this->setLevel($parent->getLevel() + 1);
		// Keep the tree modification query for the save() transaction
		$this->nestedSetQueries []= array(
			'callable'  => array('cre8MenuItemPeer', 'makeRoomForLeaf'),
			'arguments' => array($left)
		);
		return $this;
	}
	
	/**
	 * Inserts the current node as prev sibling given $sibling node
	 * The modifications in the current object and the tree
	 * are not persisted until the current object is saved.
	 *
	 * @param      cre8MenuItem $sibling	Propel object for parent node
	 *
	 * @return     cre8MenuItem The current Propel object
	 */
	public function insertAsPrevSiblingOf($sibling)
	{
		if ($this->isInTree()) {
			throw new PropelException('A cre8MenuItem object must not already be in the tree to be inserted. Use the moveToPrevSiblingOf() instead.');
		}
		$left = $sibling->getLeftValue();
		// Update node properties
		$this->setLeftValue($left);
		$this->setRightValue($left + 1);
		$this->setLevel($sibling->getLevel());
		// Keep the tree modification query for the save() transaction
		$this->nestedSetQueries []= array(
			'callable'  => array('cre8MenuItemPeer', 'makeRoomForLeaf'),
			'arguments' => array($left)
		);
		return $this;
	}
	
	/**
	 * Inserts the current node as next sibling given $sibling node
	 * The modifications in the current object and the tree
	 * are not persisted until the current object is saved.
	 *
	 * @param      cre8MenuItem $sibling	Propel object for parent node
	 *
	 * @return     cre8MenuItem The current Propel object
	 */
	public function insertAsNextSiblingOf($sibling)
	{
		if ($this->isInTree()) {
			throw new PropelException('A cre8MenuItem object must not already be in the tree to be inserted. Use the moveToNextSiblingOf() instead.');
		}
		$left = $sibling->getRightValue() + 1;
		// Update node properties
		$this->setLeftValue($left);
		$this->setRightValue($left + 1);
		$this->setLevel($sibling->getLevel());
		// Keep the tree modification query for the save() transaction
		$this->nestedSetQueries []= array(
			'callable'  => array('cre8MenuItemPeer', 'makeRoomForLeaf'),
			'arguments' => array($left)
		);
		return $this;
	}
	
	/**
	 * Moves current node and its subtree to be the first child of $parent
	 * The modifications in the current object and the tree are immediate
	 *
	 * @param      cre8MenuItem $parent	Propel object for parent node
	 * @param      PropelPDO $con	Connection to use.
	 *
	 * @return     cre8MenuItem The current Propel object
	 */
	public function moveToFirstChildOf($parent, PropelPDO $con = null)
	{
		if (!$this->isInTree()) {
			throw new PropelException('A cre8MenuItem object must be already in the tree to be moved. Use the insertAsFirstChildOf() instead.');
		}
		if ($parent->isDescendantOf($this)) {
			throw new PropelException('Cannot move a node as child of one of its subtree nodes.');
		}
		
		$this->moveSubtreeTo($parent->getLeftValue() + 1, $parent->getLevel() - $this->getLevel() + 1, $con);
		
		return $this;
	}
	
	/**
	 * Moves current node and its subtree to be the last child of $parent
	 * The modifications in the current object and the tree are immediate
	 *
	 * @param      cre8MenuItem $parent	Propel object for parent node
	 * @param      PropelPDO $con	Connection to use.
	 *
	 * @return     cre8MenuItem The current Propel object
	 */
	public function moveToLastChildOf($parent, PropelPDO $con = null)
	{
		if (!$this->isInTree()) {
			throw new PropelException('A cre8MenuItem object must be already in the tree to be moved. Use the insertAsLastChildOf() instead.');
		}
		if ($parent->isDescendantOf($this)) {
			throw new PropelException('Cannot move a node as child of one of its subtree nodes.');
		}
		
		$this->moveSubtreeTo($parent->getRightValue(), $parent->getLevel() - $this->getLevel() + 1, $con);
		
		return $this;
	}
	
	/**
	 * Moves current node and its subtree to be the previous sibling of $sibling
	 * The modifications in the current object and the tree are immediate
	 *
	 * @param      cre8MenuItem $sibling	Propel object for sibling node
	 * @param      PropelPDO $con	Connection to use.
	 *
	 * @return     cre8MenuItem The current Propel object
	 */
	public function moveToPrevSiblingOf($sibling, PropelPDO $con = null)
	{
		if (!$this->isInTree()) {
			throw new PropelException('A cre8MenuItem object must be already in the tree to be moved. Use the insertAsPrevSiblingOf() instead.');
		}
		if ($sibling->isRoot()) {
			throw new PropelException('Cannot move to previous sibling of a root node.');
		}
		if ($sibling->isDescendantOf($this)) {
			throw new PropelException('Cannot move a node as sibling of one of its subtree nodes.');
		}
		
		$this->moveSubtreeTo($sibling->getLeftValue(), $sibling->getLevel() - $this->getLevel(), $con);
		
		return $this;
	}
	
	/**
	 * Moves current node and its subtree to be the next sibling of $sibling
	 * The modifications in the current object and the tree are immediate
	 *
	 * @param      cre8MenuItem $sibling	Propel object for sibling node
	 * @param      PropelPDO $con	Connection to use.
	 *
	 * @return     cre8MenuItem The current Propel object
	 */
	public function moveToNextSiblingOf($sibling, PropelPDO $con = null)
	{
		if (!$this->isInTree()) {
			throw new PropelException('A cre8MenuItem object must be already in the tree to be moved. Use the insertAsNextSiblingOf() instead.');
		}
		if ($sibling->isRoot()) {
			throw new PropelException('Cannot move to next sibling of a root node.');
		}
		if ($sibling->isDescendantOf($this)) {
			throw new PropelException('Cannot move a node as sibling of one of its subtree nodes.');
		}
		
		$this->moveSubtreeTo($sibling->getRightValue() + 1, $sibling->getLevel() - $this->getLevel(), $con);
		
		return $this;
	}
	
	/**
	 * Move current node and its children to location $destLeft and updates rest of tree
	 *
	 * @param      int	$destLeft Destination left value
	 * @param      int	$levelDelta Delta to add to the levels
	 * @param      PropelPDO $con		Connection to use.
	 */
	protected function moveSubtreeTo($destLeft, $levelDelta, PropelPDO $con = null)
	{
		$left  = $this->getLeftValue();
		$right = $this->getRightValue();
	
		$treeSize = $right - $left +1;
		
		if ($con === null) {
			$con = Propel::getConnection(cre8MenuItemPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
			
		$con->beginTransaction();
		try {
			// make room next to the target for the subtree
			cre8MenuItemPeer::shiftRLValues($treeSize, $destLeft, null, $con);
		
			if ($left >= $destLeft) { // src was shifted too?
				$left += $treeSize;
				$right += $treeSize;
			}
			
			if ($levelDelta) {
				// update the levels of the subtree
				cre8MenuItemPeer::shiftLevel($levelDelta, $left, $right, $con);
			}
			
			// move the subtree to the target
			cre8MenuItemPeer::shiftRLValues($destLeft - $left, $left, $right, $con);
		
			// remove the empty room at the previous location of the subtree
			cre8MenuItemPeer::shiftRLValues(-$treeSize, $right + 1, null, $con);
			
			// update all loaded nodes
			cre8MenuItemPeer::updateLoadedNodes($con);
			
			$con->commit();
		} catch (PropelException $e) {
			$con->rollback();
			throw $e;
		}
	}
	
	/**
	 * Deletes all descendants for the given node
	 * Instance pooling is wiped out by this command, 
	 * so existing cre8MenuItem instances are probably invalid (except for the current one)
	 *
	 * @param      PropelPDO $con Connection to use.
	 *
	 * @return     int 		number of deleted nodes
	 */
	public function deleteDescendants(PropelPDO $con = null)
	{
		if($this->isLeaf()) {
			// save one query
			return;
		}
		if ($con === null) {
			$con = Propel::getConnection(cre8MenuItemPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		$left = $this->getLeftValue();
		$right = $this->getRightValue();
		$criteria = new Criteria(cre8MenuItemPeer::DATABASE_NAME);
		$criteria->add(cre8MenuItemPeer::LEFT_COL, $left, Criteria::GREATER_THAN);
		$criteria->add(cre8MenuItemPeer::RIGHT_COL, $right, Criteria::LESS_THAN);
		$con->beginTransaction();
		try {
			// delete descendant nodes (will empty the instance pool)
			$ret = cre8MenuItemPeer::doDelete($criteria, $con);
			
			// fill up the room that was used by descendants
			cre8MenuItemPeer::shiftRLValues($left - $right + 1, $right, null, $con);
			
			// fix the right value for the current node, which is now a leaf
			$this->setRightValue($left + 1);
			
			$con->commit();
		} catch (Exception $e) {
			$con->rollback();
			throw $e;
		}
		
		return $ret;
	}
	
	/**
	 * Returns a pre-order iterator for this node and its children.
	 *
	 * @return     RecursiveIterator
	 */
	public function getIterator()
	{
		return new NestedSetRecursiveIterator($this);
	}

	// soft_delete behavior
	
	/**
	 * Bypass the soft_delete behavior and force a hard delete of the current object
	 */
	public function forceDelete(PropelPDO $con = null)
	{
		cre8MenuItemPeer::disableSoftDelete();
		$this->delete($con);
	}
	
	/**
	 * Undelete a row that was soft_deleted
	 *
	 * @return     int The number of rows affected by this update and any referring fk objects' save() operations.
	 */
	public function unDelete(PropelPDO $con = null)
	{
		$this->setDeletedAt(null);
		return $this->save($con);
	}

	// sluggable behavior
	
	/**
	 * Create a unique slug based on the object
	 *
	 * @return string The object slug
	 */
	protected function createSlug()
	{
		$slug = $this->createRawSlug();
		$slug = $this->limitSlugSize($slug);
		$slug = $this->makeSlugUnique($slug);
		
		return $slug;
	}
	
	/**
	 * Create the slug from the appropriate columns
	 *
	 * @return string
	 */
	protected function createRawSlug()
	{
		return $this->cleanupSlugPart($this->__toString());
	}
	
	/**
	 * Cleanup a string to make a slug of it
	 * Removes special characters, replaces blanks with a separator, and trim it
	 *
	 * @param     string $text      the text to slugify
	 * @param     string $separator the separator used by slug
	 * @return    string             the slugified text
	 */
	protected static function cleanupSlugPart($slug, $replacement = '-')
	{
		// transliterate
		if (function_exists('iconv')) {
			$slug = iconv('utf-8', 'us-ascii//TRANSLIT', $slug);
		}
		
		// lowercase
		if (function_exists('mb_strtolower')) {
			$slug = mb_strtolower($slug);
		} else {
			$slug = strtolower($slug);
		}
		
		// remove accents resulting from OSX's iconv
		$slug = str_replace(array('\'', '`', '^'), '', $slug);
		
		// replace non letter or digits with separator
		$slug = preg_replace('/\W+/', $replacement, $slug);
		
		// trim
		$slug = trim($slug, $replacement);
	
		if (empty($slug)) {
			return 'n-a';
		}
	
		return $slug;
	}
	
	
	/**
	 * Make sure the slug is short enough to accomodate the column size
	 *
	 * @param	string $slug			the slug to check
	 *
	 * @return string						the truncated slug
	 */
	protected static function limitSlugSize($slug, $incrementReservedSpace = 3)
	{
		// check length, as suffix could put it over maximum
		if (strlen($slug) > (255 - $incrementReservedSpace)) {
			$slug = substr($slug, 0, 255 - $incrementReservedSpace);
		}
		return $slug;
	}
	
	
	/**
	 * Get the slug, ensuring its uniqueness
	 *
	 * @param	string $slug			the slug to check
	 * @param	string $separator the separator used by slug
	 * @return string						the unique slug
	 */
	protected function makeSlugUnique($slug, $separator = '-', $increment = 0)
	{
		$slug2 = empty($increment) ? $slug : $slug . $separator . $increment;
		$slugAlreadyExists = cre8MenuItemQuery::create()
			->filterBySlug($slug2)
			->prune($this)
			->includeDeleted()
			->count();
		if ($slugAlreadyExists) {
			return $this->makeSlugUnique($slug, $separator, ++$increment);
		} else {
			return $slug2;
		}
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('Basecre8MenuItem:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method Basecre8MenuItem::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

	/**
	 * Return the string representation of this object
	 *
	 * @return string The value of the 'label' column
	 */
  public function __toString()
  {
    return (string) $this->getLabel();
  }

} // Basecre8MenuItem
